### ISSUE TITLE
Technical setup

### ISSUE THREAD

**Issue by glatard** [big-data-lab-team/big-data-lab-team.github.io#2]
Basic HTML / CSS. 
Avoid any proprietary or heavy technologies: no flash, etc

**Comment by remram44** [comment]
This doesn't have the right name to render at either [big-data-lab-team.github.io](http://big-data-lab-team.github.io/) or [bin.github.io](http://bin.github.io/)

**Comment by YongpingGao** [comment]
@glatard  This repo's name should be changed to "big-data-lab-team.github.io"

**Comment by glatard** [comment]
Right, done.
